/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChandapuraBangaloreRouteImport } from './routes/chandapura-bangalore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MuthanallurOffSarjapuraBangaloreRouteImport } from './routes/muthanallur-off-sarjapura-bangalore'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsOrleanRouteImport } from './routes/projects.orlean'
import { Route as ProjectsTheClanRouteImport } from './routes/projects.the-clan'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

const ChandapuraBangaloreRoute = ChandapuraBangaloreRouteImport.update({
  id: '/chandapura-bangalore',
  path: '/chandapura-bangalore',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const MuthanallurOffSarjapuraBangaloreRoute = MuthanallurOffSarjapuraBangaloreRouteImport.update({
  id: '/muthanallur-off-sarjapura-bangalore',
  path: '/muthanallur-off-sarjapura-bangalore',
  getParentRoute: () => rootRouteImport,
} as any)

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)

const ProjectsOrleanRoute = ProjectsOrleanRouteImport.update({
  id: '/projects/orlean',
  path: '/projects/orlean',
  getParentRoute: () => rootRouteImport,
} as any)

const ProjectsTheClanRoute = ProjectsTheClanRouteImport.update({
  id: '/projects/the-clan',
  path: '/projects/the-clan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/chandapura-bangalore': typeof ChandapuraBangaloreRoute
  '/': typeof IndexRoute
  '/muthanallur-off-sarjapura-bangalore': typeof MuthanallurOffSarjapuraBangaloreRoute
  '/projects': typeof ProjectsRoute
  '/projects/orlean': typeof ProjectsOrleanRoute
  '/projects/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/chandapura-bangalore': typeof ChandapuraBangaloreRoute
  '/': typeof IndexRoute
  '/muthanallur-off-sarjapura-bangalore': typeof MuthanallurOffSarjapuraBangaloreRoute
  '/projects': typeof ProjectsRoute
  '/projects/orlean': typeof ProjectsOrleanRoute
  '/projects/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/chandapura-bangalore': typeof ChandapuraBangaloreRoute
  '/': typeof IndexRoute
  '/muthanallur-off-sarjapura-bangalore': typeof MuthanallurOffSarjapuraBangaloreRoute
  '/projects': typeof ProjectsRoute
  '/projects/orlean': typeof ProjectsOrleanRoute
  '/projects/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/chandapura-bangalore'
    | '/'
    | '/muthanallur-off-sarjapura-bangalore'
    | '/projects'
    | '/projects/orlean'
    | '/projects/the-clan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/chandapura-bangalore'
    | '/'
    | '/muthanallur-off-sarjapura-bangalore'
    | '/projects'
    | '/projects/orlean'
    | '/projects/the-clan'
  id:
    | '__root__'
    | '/about'
    | '/chandapura-bangalore'
    | '/'
    | '/muthanallur-off-sarjapura-bangalore'
    | '/projects'
    | '/projects/orlean'
    | '/projects/the-clan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  ChandapuraBangaloreRoute: typeof ChandapuraBangaloreRoute
  IndexRoute: typeof IndexRoute
  MuthanallurOffSarjapuraBangaloreRoute: typeof MuthanallurOffSarjapuraBangaloreRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectsOrleanRoute: typeof ProjectsOrleanRoute
  ProjectsTheClanRoute: typeof ProjectsTheClanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chandapura-bangalore': {
      id: '/chandapura-bangalore'
      path: '/chandapura-bangalore'
      fullPath: '/chandapura-bangalore'
      preLoaderRoute: typeof ChandapuraBangaloreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muthanallur-off-sarjapura-bangalore': {
      id: '/muthanallur-off-sarjapura-bangalore'
      path: '/muthanallur-off-sarjapura-bangalore'
      fullPath: '/muthanallur-off-sarjapura-bangalore'
      preLoaderRoute: typeof MuthanallurOffSarjapuraBangaloreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/orlean': {
      id: '/projects/orlean'
      path: '/projects/orlean'
      fullPath: '/projects/orlean'
      preLoaderRoute: typeof ProjectsOrleanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/the-clan': {
      id: '/projects/the-clan'
      path: '/projects/the-clan'
      fullPath: '/projects/the-clan'
      preLoaderRoute: typeof ProjectsTheClanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  ChandapuraBangaloreRoute: ChandapuraBangaloreRoute,
  IndexRoute: IndexRoute,
  MuthanallurOffSarjapuraBangaloreRoute: MuthanallurOffSarjapuraBangaloreRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectsOrleanRoute: ProjectsOrleanRoute,
  ProjectsTheClanRoute: ProjectsTheClanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
