/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsandconditionsRouteImport } from './routes/termsandconditions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MuthanallurOffSarjapuraBangaloreRouteImport } from './routes/muthanallur-off-sarjapura-bangalore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChandapuraBangaloreRouteImport } from './routes/chandapura-bangalore'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsTheClanRouteImport } from './routes/projects_.the-clan'
import { Route as ProjectsOrleanRouteImport } from './routes/projects_.orlean'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const TermsandconditionsRoute = TermsandconditionsRouteImport.update({
  id: '/termsandconditions',
  path: '/termsandconditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MuthanallurOffSarjapuraBangaloreRoute =
  MuthanallurOffSarjapuraBangaloreRouteImport.update({
    id: '/muthanallur-off-sarjapura-bangalore',
    path: '/muthanallur-off-sarjapura-bangalore',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChandapuraBangaloreRoute = ChandapuraBangaloreRouteImport.update({
  id: '/chandapura-bangalore',
  path: '/chandapura-bangalore',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTheClanRoute = ProjectsTheClanRouteImport.update({
  id: '/projects_/the-clan',
  path: '/projects/the-clan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOrleanRoute = ProjectsOrleanRouteImport.update({
  id: '/projects_/orlean',
  path: '/projects/orlean',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/chandapura-bangalore': typeof ChandapuraBangaloreRoute
  '/contact': typeof ContactRoute
  '/muthanallur-off-sarjapura-bangalore': typeof MuthanallurOffSarjapuraBangaloreRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/termsandconditions': typeof TermsandconditionsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects/orlean': typeof ProjectsOrleanRoute
  '/projects/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/chandapura-bangalore': typeof ChandapuraBangaloreRoute
  '/contact': typeof ContactRoute
  '/muthanallur-off-sarjapura-bangalore': typeof MuthanallurOffSarjapuraBangaloreRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/termsandconditions': typeof TermsandconditionsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects/orlean': typeof ProjectsOrleanRoute
  '/projects/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/chandapura-bangalore': typeof ChandapuraBangaloreRoute
  '/contact': typeof ContactRoute
  '/muthanallur-off-sarjapura-bangalore': typeof MuthanallurOffSarjapuraBangaloreRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/termsandconditions': typeof TermsandconditionsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects_/orlean': typeof ProjectsOrleanRoute
  '/projects_/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/chandapura-bangalore'
    | '/contact'
    | '/muthanallur-off-sarjapura-bangalore'
    | '/privacy-policy'
    | '/projects'
    | '/termsandconditions'
    | '/blogs/$slug'
    | '/projects/orlean'
    | '/projects/the-clan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/chandapura-bangalore'
    | '/contact'
    | '/muthanallur-off-sarjapura-bangalore'
    | '/privacy-policy'
    | '/projects'
    | '/termsandconditions'
    | '/blogs/$slug'
    | '/projects/orlean'
    | '/projects/the-clan'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/chandapura-bangalore'
    | '/contact'
    | '/muthanallur-off-sarjapura-bangalore'
    | '/privacy-policy'
    | '/projects'
    | '/termsandconditions'
    | '/blogs/$slug'
    | '/projects_/orlean'
    | '/projects_/the-clan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ChandapuraBangaloreRoute: typeof ChandapuraBangaloreRoute
  ContactRoute: typeof ContactRoute
  MuthanallurOffSarjapuraBangaloreRoute: typeof MuthanallurOffSarjapuraBangaloreRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectsRoute: typeof ProjectsRoute
  TermsandconditionsRoute: typeof TermsandconditionsRoute
  ProjectsOrleanRoute: typeof ProjectsOrleanRoute
  ProjectsTheClanRoute: typeof ProjectsTheClanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termsandconditions': {
      id: '/termsandconditions'
      path: '/termsandconditions'
      fullPath: '/termsandconditions'
      preLoaderRoute: typeof TermsandconditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muthanallur-off-sarjapura-bangalore': {
      id: '/muthanallur-off-sarjapura-bangalore'
      path: '/muthanallur-off-sarjapura-bangalore'
      fullPath: '/muthanallur-off-sarjapura-bangalore'
      preLoaderRoute: typeof MuthanallurOffSarjapuraBangaloreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chandapura-bangalore': {
      id: '/chandapura-bangalore'
      path: '/chandapura-bangalore'
      fullPath: '/chandapura-bangalore'
      preLoaderRoute: typeof ChandapuraBangaloreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/the-clan': {
      id: '/projects_/the-clan'
      path: '/projects/the-clan'
      fullPath: '/projects/the-clan'
      preLoaderRoute: typeof ProjectsTheClanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/orlean': {
      id: '/projects_/orlean'
      path: '/projects/orlean'
      fullPath: '/projects/orlean'
      preLoaderRoute: typeof ProjectsOrleanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ChandapuraBangaloreRoute: ChandapuraBangaloreRoute,
  ContactRoute: ContactRoute,
  MuthanallurOffSarjapuraBangaloreRoute: MuthanallurOffSarjapuraBangaloreRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectsRoute: ProjectsRoute,
  TermsandconditionsRoute: TermsandconditionsRoute,
  ProjectsOrleanRoute: ProjectsOrleanRoute,
  ProjectsTheClanRoute: ProjectsTheClanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
