/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsTheClanRouteImport } from './routes/projects.the-clan'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)

const ProjectsTheClanRoute = ProjectsTheClanRouteImport.update({
  id: '/projects/the-clan',
  path: '/projects/the-clan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/projects/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/projects/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/projects/the-clan': typeof ProjectsTheClanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/' | '/projects' | '/projects/the-clan'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/' | '/projects' | '/projects/the-clan'
  id: '__root__' | '/about' | '/' | '/projects' | '/projects/the-clan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectsTheClanRoute: typeof ProjectsTheClanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/the-clan': {
      id: '/projects/the-clan'
      path: '/projects/the-clan'
      fullPath: '/projects/the-clan'
      preLoaderRoute: typeof ProjectsTheClanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectsTheClanRoute: ProjectsTheClanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
